name: Build images
on:
  push:
    branches:
      - main
  pull_request:
  pull_request_target:
    branches:
      - main

env:
  TAG_NAME: 3.1.3-alpine
  USER_NAME: ledermann

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push BUILDER image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: ./Builder
          file: ./Builder/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.USER_NAME }}/rails-base-builder:${{ env.TAG_NAME }}
            ${{ env.USER_NAME }}/rails-base-builder:${{ env.TAG_NAME }}
            ghcr.io/${{ env.USER_NAME }}/rails-base-builder:latest
            ${{ env.USER_NAME }}/rails-base-builder:latest

      - name: Build and push FINAL image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: ./Final
          file: ./Final/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.USER_NAME }}/rails-base-final:${{ env.TAG_NAME }}
            ${{ env.USER_NAME }}/rails-base-final:${{ env.TAG_NAME }}
            ghcr.io/${{ env.USER_NAME }}/rails-base-final:latest
            ${{ env.USER_NAME }}/rails-base-final:latest
